version: "3.7"
services:

    php-fpm:
        build: php-docker
        container_name: cab-php
        working_dir: /app
        environment:
            - PHP_MEMORY_LIMIT=-1
            - WEB_DOCUMENT_ROOT=/app/public
        volumes:
            - .:/app
        ports:
            - "9080:80"

    database:
        image: mysql:8.0.20
        container_name: cab-db
        command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '9306:3306'
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
